/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "SPI.h"
#include "Console.h"
#include "W25Qx_Driver.h"


W25Qx_Typedef W25QX16;

int main(void)
{
	W25QX16.SPI_Port = SPI1;
	W25QX16.pin_remap = true;

	MCU_Clock_Setup();
	Console_Init(USART1, 460800);
	Delay_Config();


	W25QX_Init(&W25QX16);
	W25Qx_Chip_Erase();

	for(;;)
	{

	}
}
