/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "SPI.h"
#include "Console.h"
#include "W25Qx_Driver.h"


W25Qx_Typedef W25QX16;

int main(void)
{
	uint8_t data[] = {11,12,13,14,15,16,17,18,19,20};
	uint8_t data1[10];
	int len = 10;
	W25QX16.SPI_Port = SPI1;
	W25QX16.pin_remap = true;
	W25QX16.nCSS_Port = GPIOA;
	W25QX16.nCSS_Pin = 15;

	MCU_Clock_Setup();
	Console_Init(USART1, 460800);
	Delay_Config();

	printConsole(USART1, "Hello \r\n");

	int32_t address = 0x102030;

	W25QX_Init(&W25QX16);
	W25Qx_Chip_Erase();



	Delay_s(1);


	W25Qx_Write_Page(&W25QX16, address, &data[0], len);

	W25Qx_Read_Page(&W25QX16, address, -1, &data1[0], len);



	for(;;)
	{

	}
}
